import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Header from "../components/UI/Header";
import Navbar from "../components/UI/Navbar";
import Headline from "../components/UI/Headline";
import Content from "../components/Content";
import Info from "../components/Info";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<Header/>
			<Navbar />
			<Headline />
			{/*<Content />*/}
			<Info />

		</div>
	);
}
