import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Header from "../components/UI/Header";
import Navbar from "../components/UI/Navbar";
import Headline from "../components/UI/Headline";
import Content from "../components/Content";
import Info from "../components/Info";
import Test from "../components/Test";
import Test2 from "../components/Test2";
import React from "react";
import ArticlesList from "../components/ArticlesList/ArticlesList";
import {server} from "../config";


export default function Home({articles}) {
	console.log(articles);
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			{/*<Header/>*/}
			{/*<Navbar />*/}
			{/*<Headline />*/}
			{/*<Content />*/}
			{/*<Info />*/}
			{/*<Test />*/}
			<ArticlesList articles={articles} />
			{/*<Test2 />*/}
			{/*{articles.map((article)=>{*/}
			{/*	return <h3 key={article.id}>{article.title}</h3>*/}
			{/*})}*/}

		</div>
	);
}

// export const getStaticProps = async () => {
// 	const res = await fetch('https://jsonplaceholder.typicode.com/posts?_limit=10')
// 	const articles = await res.json()
// 	console.log(articles);
// 	return {
// 		props: {
// 			articles,
// 		},
// 	};
// };
export const getStaticProps = async () => {
	const res = await fetch(`${server}/api/articles`)
	const articles = await res.json()
	console.log(articles[0].title);
	return {
		props: {
			articles,
		},
	};
};